variable root_volume_size {}
variable global_bastion_sg {}
variable global_key_name {}             
variable global_vpc_id {}               
variable global_zone_id {}              
variable kong_ami {}      
variable kong_keypair {}             
variable kong_cluster_size {}       
variable kong_dns_name {}              
variable kong_instance_type {}         
variable kong_puppet_environment {}   
variable kong_puppet_instance_tier {}  
variable kong_subnet_ids {}            
variable kong_tag_contact {}          
variable kong_tag_cost_code {}        
variable kong_tag_environment {}      
variable kong_tag_orchestration {}    
variable kong_tag_product {}           
variable kong_tag_sub_product {}      
